#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
NAME="smp3-multipath-kit-alpha2.3-r11"
STAGE_ROOT="${STAGE_ROOT:-$ROOT/.release-stage}"
STAGE="$STAGE_ROOT/$NAME"
OUT_ZIP="${1:-$ROOT/$NAME-source.zip}"

LINUX_BIN="$ROOT/dist/smp3-proxy-linux-amd64"
WINDOWS_BIN="$ROOT/dist/smp3-proxy-windows-amd64.exe"
HAVE_BINARIES=0
if [ -x "$LINUX_BIN" ] && [ -f "$WINDOWS_BIN" ]; then
  HAVE_BINARIES=1
elif [ -e "$LINUX_BIN" ] || [ -e "$WINDOWS_BIN" ]; then
  echo "only one final binary is present; remove it or run ./build.sh to produce both" >&2
  exit 1
fi

rm -rf "$STAGE"
mkdir -p "$STAGE" "$STAGE/dist" "$STAGE/config" "$STAGE/patches" "$STAGE/scripts" "$STAGE/src"

for f in README.md README-zh_CN.md RELEASE_NOTES.md CHANGELOG.md BUILD_STATUS.md TEST_RESULTS.txt R11_ACCEPTANCE.md \
         SECURITY.md NOTICE.md VERSION build.sh validate-kit.sh install-server.sh install-client.ps1 \
         package-release.sh UPGRADE-alpha2-to-alpha2.1.md UPGRADE-alpha2.1-to-alpha2.2.md; do
  [ -f "$ROOT/$f" ] && cp -a "$ROOT/$f" "$STAGE/$f"
done
cp -a "$ROOT/config/." "$STAGE/config/"
cp -a "$ROOT/patches/." "$STAGE/patches/"
cp -a "$ROOT/scripts/." "$STAGE/scripts/"
cp -a "$ROOT/src/." "$STAGE/src/"

if [ "$HAVE_BINARIES" -eq 1 ]; then
  cp -a "$LINUX_BIN" "$WINDOWS_BIN" "$STAGE/dist/"
else
  cp -a "$ROOT/dist/BUILD_REQUIRED.md" "$STAGE/dist/"
fi

# Never ship local deployment configs, caches, logs, editor files or generated bytecode.
find "$STAGE" -type d \( -name .git -o -name .work -o -name .release-stage -o -name __pycache__ \) -prune -exec rm -rf {} +
find "$STAGE" -type f \( \
  -name '*.pyc' -o -name '*.pyo' -o -name '*.log' -o -name '*.tmp' -o -name '*.bak' -o \
  -name 'dist.zip' -o -name 'config.json' -o -name 'client.json' -o -name 'server.json' -o \
  -name '*.key' -o -name '*.pem' -o -name '*.p12' -o -name '*.pfx' \
\) -delete

chmod 0755 "$STAGE/build.sh" "$STAGE/validate-kit.sh" "$STAGE/install-server.sh" "$STAGE/package-release.sh"
find "$STAGE/scripts" -maxdepth 1 -type f -name '*.sh' -exec chmod 0755 {} +
find "$STAGE" -type f -name '*.json' -exec chmod 0644 {} +
if [ "$HAVE_BINARIES" -eq 1 ]; then
  chmod 0755 "$STAGE/dist/smp3-proxy-linux-amd64"
fi

# Validate that example secret fields remain placeholders rather than deployment credentials.
python3 - "$STAGE/config" <<'PY'
import json, pathlib, sys
root = pathlib.Path(sys.argv[1])
secret_keys = {'password', 'psk', 'obfs_password', 'key', 'private_key', 'token', 'api_key'}
allowed_prefixes = ('YOUR_', 'CHANGE_')
problems=[]
def walk(v, path):
    if isinstance(v, dict):
        for k, x in v.items():
            kl=k.lower()
            if kl in secret_keys and isinstance(x, str) and x and not x.startswith(allowed_prefixes):
                # Certificate/key filesystem paths are not secret values themselves.
                if kl in {'key', 'private_key'} and ('/' in x or '\\' in x):
                    pass
                else:
                    problems.append(f'{path}: {k} is not a placeholder')
            walk(x, path)
    elif isinstance(v, list):
        for x in v:
            walk(x, path)
for p in root.glob('*.json'):
    with p.open(encoding='utf-8') as f:
        walk(json.load(f), p.name)
if problems:
    raise SystemExit('\n'.join(problems))
PY

# Reject obvious machine/user-specific release debris.
if grep -RIlE --exclude='MANIFEST.sha256' --exclude='package-release.sh' \
  '(-----BEGIN (RSA |EC |OPENSSH |PRIVATE )?PRIVATE KEY-----|/home/[^/[:space:]]+/|C:\\Users\\[^\\[:space:]]+\\)' \
  "$STAGE" | grep -q .; then
  echo 'release staging contains an obvious private key or user-specific absolute home path' >&2
  exit 1
fi

if [ "$HAVE_BINARIES" -eq 1 ]; then
  (
    cd "$STAGE/dist"
    sha256sum smp3-proxy-linux-amd64 smp3-proxy-windows-amd64.exe > SHA256SUMS
    sha256sum -c SHA256SUMS
  )
fi

# Source/release manifest excludes itself and binary checksums/binaries to avoid cycles.
(
  cd "$STAGE"
  find . -type f \
    ! -path './MANIFEST.sha256' \
    ! -path './dist/SHA256SUMS' \
    ! -path './dist/smp3-proxy-linux-amd64' \
    ! -path './dist/smp3-proxy-windows-amd64.exe' \
    -print0 | sort -z | xargs -0 sha256sum > MANIFEST.sha256
  sha256sum -c MANIFEST.sha256
)

if find "$STAGE" \( -name .git -o -name .work -o -name .release-stage -o -name __pycache__ \) -print | grep -q .; then
  echo 'release staging contains forbidden metadata/cache' >&2
  exit 1
fi

rm -f "$OUT_ZIP" "$OUT_ZIP.sha256"
if command -v zip >/dev/null 2>&1; then
  (
    cd "$STAGE_ROOT"
    zip -q -r "$OUT_ZIP" "$NAME"
  )
elif command -v powershell.exe >/dev/null 2>&1 && command -v wslpath >/dev/null 2>&1; then
  # The closeout host may have Windows PowerShell but no WSL zip package.
  # Preserve the same top-level release directory in the archive.
  OUT_ZIP_WIN="$(wslpath -w "$OUT_ZIP")"
  STAGE_WIN="$(wslpath -w "$STAGE")"
  powershell.exe -NoProfile -Command "Compress-Archive -Path '$STAGE_WIN' -DestinationPath '$OUT_ZIP_WIN' -Force"
else
  echo 'missing zip (or Windows PowerShell fallback)' >&2
  exit 1
fi
sha256sum "$OUT_ZIP" > "$OUT_ZIP.sha256"

if [ "$HAVE_BINARIES" -eq 1 ]; then
  echo "[+] binary release: $OUT_ZIP"
else
  echo "[+] clean source candidate: $OUT_ZIP"
fi
echo "[+] sha256: $OUT_ZIP.sha256"
