package server

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"strconv"
	"sync"
	"sync/atomic"
	"time"

	smp3core "github.com/Superbias/smp3-multipath-kit-public/smp3core"
)

type TelemetryConfig struct {
	Enabled            bool
	SnapshotInterval   time.Duration
	MaxActiveSessions  int
	MaxEvents          int
	CloseGrace         time.Duration
	HMACSecret         []byte
	AccountingPath     string
	AccountingTimezone string
	AccountingInterval time.Duration
}

// TelemetryOptions is intentionally disabled by default and contains no
// secret-bearing field. The process-local HMAC secret is generated by the
// registry and is never loaded from or written to config.
type TelemetryOptions struct {
	Enabled            bool     `json:"enabled"`
	Listen             string   `json:"listen"`
	SnapshotInterval   Duration `json:"snapshot_interval"`
	MaxActiveSessions  int      `json:"max_active_sessions"`
	MaxEvents          int      `json:"max_events"`
	CloseGrace         Duration `json:"close_grace"`
	AccountingPath     string   `json:"accounting_path"`
	AccountingTimezone string   `json:"accounting_timezone"`
	AccountingInterval Duration `json:"accounting_interval"`
}

func (o TelemetryOptions) registryConfig() TelemetryConfig {
	return TelemetryConfig{
		Enabled:            o.Enabled,
		SnapshotInterval:   o.SnapshotInterval.Time(),
		MaxActiveSessions:  o.MaxActiveSessions,
		MaxEvents:          o.MaxEvents,
		CloseGrace:         o.CloseGrace.Time(),
		AccountingPath:     o.AccountingPath,
		AccountingTimezone: o.AccountingTimezone,
		AccountingInterval: o.AccountingInterval.Time(),
	}
}

func (o *TelemetryOptions) NormalizeAndValidate() error {
	if !o.Enabled {
		return nil
	}
	if o.AccountingTimezone == "" {
		o.AccountingTimezone = "UTC"
	}
	if o.AccountingInterval.Time() <= 0 {
		o.AccountingInterval = Duration(10 * time.Second)
	}
	if _, err := time.LoadLocation(o.AccountingTimezone); err != nil {
		return fmt.Errorf("invalid telemetry.accounting_timezone %q: %w", o.AccountingTimezone, err)
	}
	if o.Listen == "" {
		o.Listen = "127.0.0.1:24500"
	}
	host, portText, err := net.SplitHostPort(o.Listen)
	if err != nil {
		return fmt.Errorf("invalid telemetry.listen %q", o.Listen)
	}
	if host != "127.0.0.1" && host != "::1" {
		return fmt.Errorf("telemetry.listen must use literal loopback 127.0.0.1 or ::1")
	}
	port, err := strconv.Atoi(portText)
	if err != nil || port < 0 || port > 65535 {
		return fmt.Errorf("invalid telemetry.listen port %q", portText)
	}
	return nil
}

type TelemetryLegSnapshot struct {
	State                string
	IngressRole          string
	Generation           uint64
	AttachAt             time.Time
	DetachAt             time.Time
	WireTxBytes          uint64
	WireRxBytes          uint64
	DataSentBytes        uint64
	FirstDataAt          time.Time
	LogicalTxAckedBytes  uint64
	LogicalRxUniqueBytes uint64
	RetransmitBytes      uint64
	RetransmitFrames     uint64
	DataAttemptFrames    uint64
	RescueAttemptFrames  uint64
	RescueAttemptBytes   uint64
}

type TelemetryStartupSnapshot struct {
	Applied                bool
	Policy                 smp3core.StreamStartupPolicy
	PreferredLeg           int8
	Grace                  time.Duration
	FirstDataWaitingAt     time.Time
	GraceStartedAt         time.Time
	PreferredAttachedAt    time.Time
	NonPreferredAttachedAt time.Time
	ReleasedAt             time.Time
	ReleaseReason          smp3core.StreamStartupReleaseReason
	FirstDataLeg           int8
}

type TelemetrySessionSnapshot struct {
	DisplaySessionID  string
	IngressRole       string
	Mode              string
	CreatedAt         time.Time
	ClosedAt          time.Time
	FirstLegReadyAt   time.Time
	FirstDataSeenAt   time.Time
	StartupReleasedAt time.Time
	StartupResult     string
	Startup           *TelemetryStartupSnapshot
	TargetTxBytes     uint64
	TargetRxBytes     uint64
	Legs              [2]TelemetryLegSnapshot
}

type TelemetryLegAggregate struct {
	ActiveSessions       uint64
	ActiveConnections    uint64
	WireTxBytes          uint64
	WireRxBytes          uint64
	WireTxRate           *float64
	WireRxRate           *float64
	DataSentBytes        uint64
	DataSentRate         *float64
	WireShare            TelemetryShare
	WireTxShare          TelemetryShare
	WireRxShare          TelemetryShare
	LogicalTxAckedBytes  uint64
	LogicalTxAckedRate   *float64
	LogicalRxUniqueBytes uint64
	LogicalRxUniqueRate  *float64
	LogicalTxShare       TelemetryShare
	LogicalRxShare       TelemetryShare
	RetransmitBytes      uint64
	RetransmitFrames     uint64
	DataAttemptFrames    uint64
	RescueAttemptFrames  uint64
	RescueAttemptBytes   uint64
}

type TelemetryRoleLegAggregate struct {
	DataSentBytes        uint64
	LogicalTxAckedBytes  uint64
	LogicalRxUniqueBytes uint64
}

type TelemetryRoleAggregate struct {
	Role                 string
	ActiveSessions       uint64
	ActiveLegs           uint64
	DataSentBytes        uint64
	LogicalTxAckedBytes  uint64
	LogicalRxUniqueBytes uint64
	Legs                 [2]TelemetryRoleLegAggregate
}

const (
	TelemetryIngressNative     = "native"
	TelemetryIngressStandalone = "standalone"
	TelemetryIngressUnknown    = "unknown"
	TelemetryIngressMixed      = "mixed"
)

func ingressRoleIndex(role string) int {
	switch role {
	case TelemetryIngressNative:
		return 0
	case TelemetryIngressStandalone:
		return 1
	case TelemetryIngressMixed:
		return 3
	default:
		return 2
	}
}

func ingressRoleForListener(sidecar bool) string {
	if sidecar {
		return TelemetryIngressStandalone
	}
	return TelemetryIngressNative
}

type TelemetrySnapshot struct {
	Timestamp                time.Time
	WindowDuration           time.Duration
	ActiveSessions           uint64
	TotalSessions            uint64
	ActiveLegs               uint64
	TotalWireTx              uint64
	TotalWireRx              uint64
	CurrentWireTxRate        *float64
	CurrentWireRxRate        *float64
	Legs                     [2]TelemetryLegAggregate
	Roles                    [4]TelemetryRoleAggregate
	Sessions                 []TelemetrySessionSnapshot
	TelemetryDroppedEvents   uint64
	RejectedCarriers         uint64
	SSESlowClientDisconnects uint64
}

type telemetryLifecycleEvent struct {
	ID               uint64
	Kind             string
	At               time.Time
	DisplaySessionID string
	Mode             string
	LegID            *uint8
	State            string
}

type telemetrySSEAggregate struct {
	SnapshotAt             time.Time
	Generation             string
	WindowDuration         time.Duration
	ActiveSessions         uint64
	TotalSessions          uint64
	ActiveLegs             uint64
	TotalWireTx            uint64
	TotalWireRx            uint64
	CurrentWireTxRate      *float64
	CurrentWireRxRate      *float64
	TelemetryDroppedEvents uint64
	Legs                   [2]TelemetryLegAggregate
	Roles                  [4]TelemetryRoleAggregate
	Traffic                *TrafficReport
}

type telemetrySSEMessage struct {
	Kind      string
	Lifecycle telemetryLifecycleEvent
	Snapshot  telemetrySSEAggregate
	Reason    string
}

type telemetrySSESubscriberState uint8

const (
	telemetrySSESubscriberNew telemetrySSESubscriberState = iota
	telemetrySSESubscriberStarting
	telemetrySSESubscriberActivating
	telemetrySSESubscriberActive
	telemetrySSESubscriberClosing
	telemetrySSESubscriberClosed
)

type telemetrySSESubscriber struct {
	id              uint64
	ch              chan telemetrySSEMessage
	state           telemetrySSESubscriberState
	cursor          uint64
	snapshotVersion uint64
}

type telemetryLegRecord struct {
	state                string
	ingressRole          string
	generation           uint64
	attachAt             time.Time
	detachAt             time.Time
	counters             *WireCounters
	dataSentBytes        uint64
	firstDataAt          time.Time
	logicalTxAckedBytes  uint64
	logicalRxUniqueBytes uint64
	retransmitBytes      uint64
	retransmitFrames     uint64
	dataAttemptFrames    uint64
	rescueAttemptFrames  uint64
	rescueAttemptBytes   uint64
}

type telemetrySessionRecord struct {
	id              smp3core.SessionID
	displayID       string
	mode            string
	createdAt       time.Time
	closedAt        time.Time
	firstLegReadyAt time.Time
	firstDataSeenAt time.Time
	startup         *TelemetryStartupSnapshot
	legs            [2]telemetryLegRecord
	stream          *smp3core.StreamEngine
	dgram           *smp3core.DatagramEngine
	targetTxBytes   atomic.Uint64
	targetRxBytes   atomic.Uint64
}

type TelemetryRegistry struct {
	cfg             TelemetryConfig
	enabled         bool
	secret          []byte
	mu              sync.RWMutex
	sessions        map[smp3core.SessionID]*telemetrySessionRecord
	total           atomic.Uint64
	dropped         atomic.Uint64
	rejected        atomic.Uint64
	events          chan struct{}
	stop            chan struct{}
	done            chan struct{}
	closeOnce       sync.Once
	latest          atomic.Value
	rateMu          sync.Mutex
	lastAt          time.Time
	lastTx          uint64
	lastRx          uint64
	lastLegTx       [2]uint64
	lastLegRx       [2]uint64
	lastLegDataSent [2]uint64
	lastLegAck      [2]uint64
	lastLegUnique   [2]uint64
	eventMu         sync.Mutex
	lifecycleRing   []telemetryLifecycleEvent
	nextEventID     atomic.Uint64
	snapshotSeq     atomic.Uint64
	subscribers     map[uint64]*telemetrySSESubscriber
	nextSubID       uint64
	sseClosed       bool
	sseSlowDrops    atomic.Uint64
}

func NewTelemetryRegistry(cfg TelemetryConfig) *TelemetryRegistry {
	if cfg.SnapshotInterval <= 0 {
		cfg.SnapshotInterval = 250 * time.Millisecond
	}
	if cfg.MaxActiveSessions <= 0 {
		cfg.MaxActiveSessions = 1024
	}
	if cfg.MaxEvents <= 0 {
		cfg.MaxEvents = 1024
	}
	if cfg.CloseGrace <= 0 {
		cfg.CloseGrace = 2 * time.Second
	}
	secret := append([]byte(nil), cfg.HMACSecret...)
	if len(secret) == 0 {
		secret = make([]byte, 32)
		_, _ = rand.Read(secret)
	}
	r := &TelemetryRegistry{
		cfg:         cfg,
		enabled:     cfg.Enabled,
		secret:      secret,
		sessions:    make(map[smp3core.SessionID]*telemetrySessionRecord),
		events:      make(chan struct{}, cfg.MaxEvents),
		stop:        make(chan struct{}),
		done:        make(chan struct{}),
		subscribers: make(map[uint64]*telemetrySSESubscriber),
	}
	if !r.enabled {
		close(r.done)
		return r
	}
	go r.snapshotLoop()
	return r
}

func (r *TelemetryRegistry) Enabled() bool { return r != nil && r.enabled }

func (r *TelemetryRegistry) RecordRejectedCarrier() {
	if r != nil && r.enabled {
		r.rejected.Add(1)
	}
}

func (r *TelemetryRegistry) Close() {
	if r == nil || !r.enabled {
		return
	}
	r.closeOnce.Do(func() {
		r.closeSSESubscribers()
		close(r.stop)
	})
	<-r.done
}

func (r *TelemetryRegistry) RegisterSession(id smp3core.SessionID, mode string, now time.Time) bool {
	return r.RegisterSessionWithRole(id, mode, TelemetryIngressUnknown, now)
}

func (r *TelemetryRegistry) RegisterSessionWithRole(id smp3core.SessionID, mode, ingressRole string, now time.Time) bool {
	if r == nil || !r.enabled {
		return true
	}
	r.mu.Lock()
	r.pruneClosedLocked(now)
	if _, exists := r.sessions[id]; exists {
		r.mu.Unlock()
		return true
	}
	if len(r.sessions) >= r.cfg.MaxActiveSessions {
		r.dropped.Add(1)
		r.mu.Unlock()
		return false
	}
	displayID := r.displayID(id)
	r.sessions[id] = &telemetrySessionRecord{id: id, displayID: displayID, mode: mode, createdAt: now}
	if ingressRole != "" {
		// The role is finalized per leg when that leg is attached. This initial
		// value is retained for single-listener sessions before the first leg
		// snapshot is available.
		r.sessions[id].legs[0].ingressRole = ingressRole
	}
	r.total.Add(1)
	r.mu.Unlock()
	r.publishLifecycle("session_created", displayID, mode, nil, now)
	return true
}

func (r *TelemetryRegistry) BindStream(id smp3core.SessionID, engine *smp3core.StreamEngine) {
	if r == nil || !r.enabled {
		return
	}
	r.mu.Lock()
	if session := r.sessions[id]; session != nil {
		session.stream = engine
	}
	r.mu.Unlock()
}

func (r *TelemetryRegistry) BindDatagram(id smp3core.SessionID, engine *smp3core.DatagramEngine) {
	if r == nil || !r.enabled {
		return
	}
	r.mu.Lock()
	if session := r.sessions[id]; session != nil {
		session.dgram = engine
	}
	r.mu.Unlock()
}

func (r *TelemetryRegistry) record(id smp3core.SessionID) *telemetrySessionRecord {
	if r == nil || !r.enabled {
		return nil
	}
	r.mu.RLock()
	record := r.sessions[id]
	r.mu.RUnlock()
	return record
}

func (r *TelemetryRegistry) AttachLeg(id smp3core.SessionID, leg uint8, generation uint64, counters *WireCounters, now time.Time) {
	r.AttachLegWithRole(id, leg, generation, counters, TelemetryIngressUnknown, now)
}

func (r *TelemetryRegistry) AttachLegWithRole(id smp3core.SessionID, leg uint8, generation uint64, counters *WireCounters, ingressRole string, now time.Time) {
	if r == nil || !r.enabled || leg >= 2 {
		return
	}
	var displayID, mode string
	var found bool
	r.mu.Lock()
	if session := r.sessions[id]; session != nil {
		found = true
		displayID, mode = session.displayID, session.mode
		if generation == 0 {
			generation = session.legs[leg].generation + 1
		}
		if ingressRole == "" {
			ingressRole = TelemetryIngressUnknown
		}
		session.legs[leg] = telemetryLegRecord{state: "up", ingressRole: ingressRole, generation: generation, attachAt: now, counters: counters}
		if session.firstLegReadyAt.IsZero() {
			session.firstLegReadyAt = now
		}
	}
	r.mu.Unlock()
	if found {
		r.publishLifecycle("leg_attached", displayID, mode, &leg, now)
	}
}

func (r *TelemetryRegistry) DetachLeg(id smp3core.SessionID, leg uint8, now time.Time) {
	if r == nil || !r.enabled || leg >= 2 {
		return
	}
	var displayID, mode string
	var found bool
	r.mu.Lock()
	if session := r.sessions[id]; session != nil {
		found = true
		displayID, mode = session.displayID, session.mode
		session.legs[leg].state = "down"
		session.legs[leg].detachAt = now
	}
	r.mu.Unlock()
	if found {
		r.publishLifecycle("leg_detached", displayID, mode, &leg, now)
	}
}

func (r *TelemetryRegistry) MarkFirstData(id smp3core.SessionID, leg uint8, now time.Time) {
	if r == nil || !r.enabled || leg >= 2 {
		return
	}
	var displayID, mode string
	var first bool
	r.mu.Lock()
	if session := r.sessions[id]; session != nil {
		displayID, mode = session.displayID, session.mode
		if session.legs[leg].firstDataAt.IsZero() {
			session.legs[leg].firstDataAt = now
			first = true
		}
		if session.firstDataSeenAt.IsZero() {
			session.firstDataSeenAt = now
		}
	}
	r.mu.Unlock()
	if first {
		r.publishLifecycle("first_data", displayID, mode, &leg, now)
	}
}

func (r *TelemetryRegistry) RemoveSession(id smp3core.SessionID, now time.Time) {
	if r == nil || !r.enabled {
		return
	}
	var displayID, mode string
	var found bool
	r.mu.Lock()
	if session := r.sessions[id]; session != nil && session.closedAt.IsZero() {
		found = true
		displayID, mode = session.displayID, session.mode
		session.closedAt = now
		for leg := range session.legs {
			if session.legs[leg].state == "up" {
				session.legs[leg].state = "down"
				session.legs[leg].detachAt = now
			}
		}
	}
	r.mu.Unlock()
	if found {
		r.publishLifecycle("session_closed", displayID, mode, nil, now)
	}
}

func (r *TelemetryRegistry) Snapshot() TelemetrySnapshot {
	if r == nil || !r.enabled {
		return TelemetrySnapshot{}
	}
	now := time.Now()
	snapshot := r.buildSnapshot(now)
	r.latest.Store(snapshot)
	return cloneTelemetrySnapshot(snapshot)
}

// LatestSnapshot returns the most recent worker-produced immutable snapshot;
// before the first worker tick it takes an immediate snapshot.
func (r *TelemetryRegistry) LatestSnapshot() TelemetrySnapshot {
	if r == nil || !r.enabled {
		return TelemetrySnapshot{}
	}
	if value := r.latest.Load(); value != nil {
		return cloneTelemetrySnapshot(value.(TelemetrySnapshot))
	}
	return r.Snapshot()
}

func (r *TelemetryRegistry) snapshotLoop() {
	ticker := time.NewTicker(r.cfg.SnapshotInterval)
	defer ticker.Stop()
	defer close(r.done)
	for {
		select {
		case <-r.stop:
			return
		case now := <-ticker.C:
			snapshot := r.buildSnapshot(now)
			r.latest.Store(snapshot)
			r.publishSnapshot(snapshot)
		}
	}
}

func (r *TelemetryRegistry) buildSnapshot(now time.Time) TelemetrySnapshot {
	r.drainEvents()
	r.mu.Lock()
	r.pruneClosedLocked(now)
	snapshot := TelemetrySnapshot{Timestamp: now, Sessions: make([]TelemetrySessionSnapshot, 0, len(r.sessions))}
	for index, role := range []string{TelemetryIngressNative, TelemetryIngressStandalone, TelemetryIngressUnknown, TelemetryIngressMixed} {
		snapshot.Roles[index].Role = role
	}
	for _, session := range r.sessions {
		r.updateFromCoreLocked(session)
		row := r.sessionSnapshot(session)
		snapshot.Sessions = append(snapshot.Sessions, row)
		if session.closedAt.IsZero() {
			snapshot.ActiveSessions++
			snapshot.Roles[ingressRoleIndex(sessionIngressRole(session))].ActiveSessions++
		}
		for leg := range session.legs {
			if session.legs[leg].state == "up" && session.closedAt.IsZero() {
				snapshot.ActiveLegs++
			}
			counters := session.legs[leg].counters.snapshot()
			if session.closedAt.IsZero() {
				snapshot.TotalWireTx += counters.TxBytes
				snapshot.TotalWireRx += counters.RxBytes
				snapshot.Legs[leg].WireTxBytes += counters.TxBytes
				snapshot.Legs[leg].WireRxBytes += counters.RxBytes
				snapshot.Legs[leg].DataSentBytes += session.legs[leg].dataSentBytes
				snapshot.Legs[leg].LogicalTxAckedBytes += session.legs[leg].logicalTxAckedBytes
				snapshot.Legs[leg].LogicalRxUniqueBytes += session.legs[leg].logicalRxUniqueBytes
				snapshot.Legs[leg].RetransmitBytes += session.legs[leg].retransmitBytes
				snapshot.Legs[leg].RetransmitFrames += session.legs[leg].retransmitFrames
				snapshot.Legs[leg].DataAttemptFrames += session.legs[leg].dataAttemptFrames
				snapshot.Legs[leg].RescueAttemptFrames += session.legs[leg].rescueAttemptFrames
				snapshot.Legs[leg].RescueAttemptBytes += session.legs[leg].rescueAttemptBytes
				if session.legs[leg].state == "up" {
					snapshot.Legs[leg].ActiveSessions++
					snapshot.Legs[leg].ActiveConnections++
					snapshot.Roles[ingressRoleIndex(session.legs[leg].ingressRole)].ActiveLegs++
				}
				roleLeg := &snapshot.Roles[ingressRoleIndex(session.legs[leg].ingressRole)].Legs[leg]
				roleLeg.DataSentBytes += session.legs[leg].dataSentBytes
				roleLeg.LogicalTxAckedBytes += session.legs[leg].logicalTxAckedBytes
				roleLeg.LogicalRxUniqueBytes += session.legs[leg].logicalRxUniqueBytes
			}
		}
	}
	r.mu.Unlock()
	wireTotal := snapshot.TotalWireTx + snapshot.TotalWireRx
	txTotal := snapshot.TotalWireTx
	rxTotal := snapshot.TotalWireRx
	logicalTxTotal := snapshot.Legs[0].LogicalTxAckedBytes + snapshot.Legs[1].LogicalTxAckedBytes
	logicalRxTotal := snapshot.Legs[0].LogicalRxUniqueBytes + snapshot.Legs[1].LogicalRxUniqueBytes
	for leg := range snapshot.Legs {
		legTotal := snapshot.Legs[leg].WireTxBytes + snapshot.Legs[leg].WireRxBytes
		snapshot.Legs[leg].WireShare = calculateTelemetryShare(legTotal, wireTotal)
		snapshot.Legs[leg].WireTxShare = calculateTelemetryShare(snapshot.Legs[leg].WireTxBytes, txTotal)
		snapshot.Legs[leg].WireRxShare = calculateTelemetryShare(snapshot.Legs[leg].WireRxBytes, rxTotal)
		snapshot.Legs[leg].LogicalTxShare = calculateTelemetryShare(snapshot.Legs[leg].LogicalTxAckedBytes, logicalTxTotal)
		snapshot.Legs[leg].LogicalRxShare = calculateTelemetryShare(snapshot.Legs[leg].LogicalRxUniqueBytes, logicalRxTotal)
	}
	for index := range snapshot.Roles {
		for leg := range snapshot.Roles[index].Legs {
			roleLeg := snapshot.Roles[index].Legs[leg]
			snapshot.Roles[index].DataSentBytes += roleLeg.DataSentBytes
			snapshot.Roles[index].LogicalTxAckedBytes += roleLeg.LogicalTxAckedBytes
			snapshot.Roles[index].LogicalRxUniqueBytes += roleLeg.LogicalRxUniqueBytes
		}
	}
	snapshot.TotalSessions = r.total.Load()
	snapshot.TelemetryDroppedEvents = r.dropped.Load()
	snapshot.RejectedCarriers = r.rejected.Load()
	snapshot.SSESlowClientDisconnects = r.sseSlowDrops.Load()
	r.updateRates(&snapshot)
	return snapshot
}

func (r *TelemetryRegistry) updateFromCoreLocked(session *telemetrySessionRecord) {
	if session.stream != nil {
		stats := session.stream.TelemetrySnapshot()
		session.startup = copyStartupSnapshot(stats.Telemetry.Startup)
		for leg := range session.legs {
			session.legs[leg].dataSentBytes = stats.TxSentBytesByLeg[leg]
			session.legs[leg].logicalTxAckedBytes = stats.TxAckedUsefulByLeg[leg]
			session.legs[leg].logicalRxUniqueBytes = stats.RxUniqueBytesByLeg[leg]
			session.legs[leg].retransmitBytes = stats.TxRetransmitBytesByLeg[leg]
			session.legs[leg].retransmitFrames = stats.Telemetry.DataTxRetransmitFrames[leg]
			session.legs[leg].dataAttemptFrames = stats.Telemetry.DataTxAttemptFrames[leg]
			session.legs[leg].rescueAttemptFrames = stats.Telemetry.RescueAttemptFrames[leg]
			session.legs[leg].rescueAttemptBytes = stats.Telemetry.RescueAttemptBytes[leg]
			first := earlierTime(stats.Telemetry.FirstTxDataAt[leg], stats.Telemetry.FirstRxUniqueDataAt[leg])
			if !first.IsZero() && (session.legs[leg].firstDataAt.IsZero() || first.Before(session.legs[leg].firstDataAt)) {
				session.legs[leg].firstDataAt = first
				r.publishLifecycle("first_data", session.displayID, session.mode, uint8Ptr(uint8(leg)), first)
			}
			if !first.IsZero() && (session.firstDataSeenAt.IsZero() || first.Before(session.firstDataSeenAt)) {
				session.firstDataSeenAt = first
			}
		}
	}
	if session.dgram != nil {
		session.startup = nil
		stats := session.dgram.Snapshot()
		for leg := range session.legs {
			session.legs[leg].dataSentBytes = stats.TxBytes[leg]
			session.legs[leg].logicalRxUniqueBytes = stats.RxUniqueBytes[leg]
		}
	}
}

func copyStartupSnapshot(startup smp3core.StreamStartupTelemetrySnapshot) *TelemetryStartupSnapshot {
	return &TelemetryStartupSnapshot{
		Applied:                startup.Applied,
		Policy:                 startup.Policy,
		PreferredLeg:           startup.PreferredLeg,
		Grace:                  startup.Grace,
		FirstDataWaitingAt:     startup.FirstDataWaitingAt,
		GraceStartedAt:         startup.GraceStartedAt,
		PreferredAttachedAt:    startup.PreferredAttachedAt,
		NonPreferredAttachedAt: startup.NonPreferredAttachedAt,
		ReleasedAt:             startup.ReleasedAt,
		ReleaseReason:          startup.ReleaseReason,
		FirstDataLeg:           startup.FirstDataLeg,
	}
}

func uint8Ptr(value uint8) *uint8 { return &value }

func earlierTime(a, b time.Time) time.Time {
	if a.IsZero() {
		return b
	}
	if b.IsZero() || a.Before(b) {
		return a
	}
	return b
}

func (r *TelemetryRegistry) sessionSnapshot(session *telemetrySessionRecord) TelemetrySessionSnapshot {
	row := TelemetrySessionSnapshot{
		DisplaySessionID: session.displayID,
		IngressRole:      sessionIngressRole(session),
		Mode:             session.mode,
		CreatedAt:        session.createdAt,
		ClosedAt:         session.closedAt,
		FirstLegReadyAt:  session.firstLegReadyAt,
		FirstDataSeenAt:  session.firstDataSeenAt,
		TargetTxBytes:    session.targetTxBytes.Load(),
		TargetRxBytes:    session.targetRxBytes.Load(),
	}
	if session.startup != nil {
		startup := *session.startup
		row.Startup = &startup
		row.StartupReleasedAt = startup.ReleasedAt
		row.StartupResult = startup.ReleaseReason.String()
	}
	for leg := range session.legs {
		counter := session.legs[leg].counters.snapshot()
		row.Legs[leg] = TelemetryLegSnapshot{
			State:                session.legs[leg].state,
			IngressRole:          session.legs[leg].ingressRole,
			Generation:           session.legs[leg].generation,
			AttachAt:             session.legs[leg].attachAt,
			DetachAt:             session.legs[leg].detachAt,
			WireTxBytes:          counter.TxBytes,
			WireRxBytes:          counter.RxBytes,
			DataSentBytes:        session.legs[leg].dataSentBytes,
			FirstDataAt:          session.legs[leg].firstDataAt,
			LogicalTxAckedBytes:  session.legs[leg].logicalTxAckedBytes,
			LogicalRxUniqueBytes: session.legs[leg].logicalRxUniqueBytes,
			RetransmitBytes:      session.legs[leg].retransmitBytes,
			RetransmitFrames:     session.legs[leg].retransmitFrames,
			DataAttemptFrames:    session.legs[leg].dataAttemptFrames,
			RescueAttemptFrames:  session.legs[leg].rescueAttemptFrames,
			RescueAttemptBytes:   session.legs[leg].rescueAttemptBytes,
		}
	}
	return row
}

func sessionIngressRole(session *telemetrySessionRecord) string {
	roles := make(map[string]struct{}, 2)
	for _, leg := range session.legs {
		if leg.ingressRole != "" && leg.ingressRole != TelemetryIngressUnknown {
			roles[leg.ingressRole] = struct{}{}
		}
	}
	switch len(roles) {
	case 0:
		return TelemetryIngressUnknown
	case 1:
		for role := range roles {
			return role
		}
	default:
		return TelemetryIngressMixed
	}
	return TelemetryIngressUnknown
}

func (r *TelemetryRegistry) updateRates(snapshot *TelemetrySnapshot) {
	r.rateMu.Lock()
	defer r.rateMu.Unlock()
	if !r.lastAt.IsZero() {
		elapsed := snapshot.Timestamp.Sub(r.lastAt)
		if elapsed > 0 {
			snapshot.WindowDuration = elapsed
			snapshot.CurrentWireTxRate = byteRate(snapshot.TotalWireTx, r.lastTx, elapsed)
			snapshot.CurrentWireRxRate = byteRate(snapshot.TotalWireRx, r.lastRx, elapsed)
			for leg := range snapshot.Legs {
				snapshot.Legs[leg].WireTxRate = byteRate(snapshot.Legs[leg].WireTxBytes, r.lastLegTx[leg], elapsed)
				snapshot.Legs[leg].WireRxRate = byteRate(snapshot.Legs[leg].WireRxBytes, r.lastLegRx[leg], elapsed)
				snapshot.Legs[leg].DataSentRate = byteRate(snapshot.Legs[leg].DataSentBytes, r.lastLegDataSent[leg], elapsed)
				snapshot.Legs[leg].LogicalTxAckedRate = byteRate(snapshot.Legs[leg].LogicalTxAckedBytes, r.lastLegAck[leg], elapsed)
				snapshot.Legs[leg].LogicalRxUniqueRate = byteRate(snapshot.Legs[leg].LogicalRxUniqueBytes, r.lastLegUnique[leg], elapsed)
			}
		}
	}
	r.lastAt = snapshot.Timestamp
	r.lastTx = snapshot.TotalWireTx
	r.lastRx = snapshot.TotalWireRx
	for leg := range snapshot.Legs {
		r.lastLegTx[leg] = snapshot.Legs[leg].WireTxBytes
		r.lastLegRx[leg] = snapshot.Legs[leg].WireRxBytes
		r.lastLegDataSent[leg] = snapshot.Legs[leg].DataSentBytes
		r.lastLegAck[leg] = snapshot.Legs[leg].LogicalTxAckedBytes
		r.lastLegUnique[leg] = snapshot.Legs[leg].LogicalRxUniqueBytes
	}
}

func byteRate(current, previous uint64, elapsed time.Duration) *float64 {
	if elapsed <= 0 || current < previous {
		return nil
	}
	value := float64(current-previous) / elapsed.Seconds()
	return &value
}

func (r *TelemetryRegistry) displayID(id smp3core.SessionID) string {
	h := hmac.New(sha256.New, r.secret)
	_, _ = h.Write(id[:])
	return hex.EncodeToString(h.Sum(nil)[:8])
}

func (r *TelemetryRegistry) pruneClosedLocked(now time.Time) {
	for id, session := range r.sessions {
		if !session.closedAt.IsZero() && now.Sub(session.closedAt) >= r.cfg.CloseGrace {
			delete(r.sessions, id)
		}
	}
}

func (r *TelemetryRegistry) noteEvent() {
	if r == nil || !r.enabled {
		return
	}
	select {
	case r.events <- struct{}{}:
	default:
		r.dropped.Add(1)
	}
}

func (r *TelemetryRegistry) drainEvents() {
	for {
		select {
		case <-r.events:
		default:
			return
		}
	}
}

func cloneTelemetrySnapshot(snapshot TelemetrySnapshot) TelemetrySnapshot {
	snapshot.Sessions = append([]TelemetrySessionSnapshot(nil), snapshot.Sessions...)
	for i := range snapshot.Sessions {
		if snapshot.Sessions[i].Startup != nil {
			startup := *snapshot.Sessions[i].Startup
			snapshot.Sessions[i].Startup = &startup
		}
	}
	return snapshot
}
